SET foreign_key_checks = 0;
TRUNCATE double_traducao;
TRUNCATE double_traducao_plataforma;

insert into double_traducao (chave, valor) values ('BOTAO_CADASTRO', '📲 Fazer cadastro');
insert into double_traducao (chave, valor) values ('BOTAO_CICLO', '↪️ Recuperação');
insert into double_traducao (chave, valor) values ('BOTAO_CONFIGURAR', '⚙️ Configurar');
insert into double_traducao (chave, valor) values ('BOTAO_DEPOSITAR', '💰 Depositar');
insert into double_traducao (chave, valor) values ('BOTAO_DESLOGAR', '🔓 Logout');
insert into double_traducao (chave, valor) values ('BOTAO_ENTRADA_AUTOMATICA', '🔄 Entrada automática');
insert into double_traducao (chave, valor) values ('BOTAO_ENTRADA_AUTOMATICA_ALTERAR_QTDE_ESPERA', 'Alterar quantidade espera de {tipo}');
insert into double_traducao (chave, valor) values ('BOTAO_ENTRADA_AUTOMATICA_DESABILITAR', 'Desabilitar entrada automática');
insert into double_traducao (chave, valor) values ('BOTAO_ENTRADA_AUTOMATICA_DESABILITAR_CICLO', 'Desabilitar recuperação após Stop LOSS');
insert into double_traducao (chave, valor) values ('BOTAO_ENTRADA_AUTOMATICA_DESABILITAR_STOP_LOSS', 'Desabilitar após Stop LOSS');
insert into double_traducao (chave, valor) values ('BOTAO_ENTRADA_AUTOMATICA_HABILITAR', 'Habilitar entrada automática');
insert into double_traducao (chave, valor) values ('BOTAO_ENTRADA_AUTOMATICA_HABILITAR_CICLO', 'Habilitar recuperação após Stop LOSS');
insert into double_traducao (chave, valor) values ('BOTAO_ENTRADA_AUTOMATICA_HABILITAR_STOP_LOSS', 'Habilitar após Stop LOSS');
insert into double_traducao (chave, valor) values ('BOTAO_ENTRADA_AUTOMATICA_TIPO', 'Alterar tipo de espera para entrada automática');
insert into double_traducao (chave, valor) values ('BOTAO_ENTRADA_AUTOMATICA_TIPO_LOSS', 'Los');
insert into double_traducao (chave, valor) values ('BOTAO_ENTRADA_AUTOMATICA_TIPO_WIN', 'Win');
insert into double_traducao (chave, valor) values ('BOTAO_GALES', '🐓 Gales');
insert into double_traducao (chave, valor) values ('BOTAO_GRUPO_VIP', '⭐ Grupo Vip');
insert into double_traducao (chave, valor) values ('BOTAO_HISTORICO', '📈 Histórico');
insert into double_traducao (chave, valor) values ('BOTAO_INICIAR', '🚀 Iniciar Robô');
insert into double_traducao (chave, valor) values ('BOTAO_INICIAR_LOSS', '🚀 Iniciar após LOSS');
insert into double_traducao (chave, valor) values ('BOTAO_INICIAR_WIN', ' Iniciar após WIN');
insert into double_traducao (chave, valor) values ('BOTAO_JA_ASSINEI', '');
insert into double_traducao (chave, valor) values ('BOTAO_LOGAR', '🔒 Já possuo cadastro');
insert into double_traducao (chave, valor) values ('BOTAO_NAO', '❌️ Não');
insert into double_traducao (chave, valor) values ('BOTAO_PARAR_ROBO', '⏹ Parar Robô');
insert into double_traducao (chave, valor) values ('BOTAO_PLANO_MENSAL', 'Plano mensal');
insert into double_traducao (chave, valor) values ('BOTAO_QUERO_ASSINAR', '');
insert into double_traducao (chave, valor) values ('BOTAO_REGISTAR_USUARIO', '➕ Registrar novo usuário');
insert into double_traducao (chave, valor) values ('BOTAO_SIM', '✔️ Sim');
insert into double_traducao (chave, valor) values ('BOTAO_STOP_LOSS', '❌ Stop LOSS');
insert into double_traducao (chave, valor) values ('BOTAO_STOP_LOSS_TIPO', 'Tipo');
insert into double_traducao (chave, valor) values ('BOTAO_STOP_LOSS_TIPO_QUANTIDADE', 'Quantidade');
insert into double_traducao (chave, valor) values ('BOTAO_STOP_LOSS_TIPO_VALOR', 'Valor');
insert into double_traducao (chave, valor) values ('BOTAO_STOP_LOSS_VALOR', 'Valor');
insert into double_traducao (chave, valor) values ('BOTAO_STOP_WIN', '✅ Stop WIN');
insert into double_traducao (chave, valor) values ('BOTAO_TELEFONE', 'Compartilhe seu contato');
insert into double_traducao (chave, valor) values ('BOTAO_TESTE_5_RODADAS', '🕹️ Teste 5 rodadas automáticas');
insert into double_traducao (chave, valor) values ('BOTAO_VALOR_APOSTA', '💸 Valor aposta');
insert into double_traducao (chave, valor) values ('BOTAO_VOLTAR', '⬅️ Voltar');
insert into double_traducao (chave, valor) values ('COLOR_BLACK', '⚫ PRETO ⚫');
insert into double_traducao (chave, valor) values ('COLOR_RED', '🔴 VERMELHO 🔴');
insert into double_traducao (chave, valor) values ('COLOR_WHITE', '⚪️ BRANCO ⚪️');
insert into double_traducao (chave, valor) values ('MSG_AG_PAGAMENTO_SUPORTE', '');
insert into double_traducao (chave, valor) values ('MSG_ASSINATURA_EMAIL', 'Informe o email que será utilizado na compra.\nEste email será utilizado para validar seu pagamento.');
insert into double_traducao (chave, valor) values ('MSG_ASSINATURA_TIPO', 'Selecione o tipo de assinatura desejado');
insert into double_traducao (chave, valor) values ('MSG_BET_1', '🔰 Entrada realizada 🔰\n💸 Valor: R$ {value} . \n🎯 Cor: {cor}');
insert into double_traducao (chave, valor) values ('MSG_BET_10', '➡️ RESULTADO: {cor}\n💸 Lucro/Prejuízo: R$ {lucro}\n\nA sua banca é de {banca}');
insert into double_traducao (chave, valor) values ('MSG_BET_11', '🚨ENTRADA CONFIRMADA🚨⚠️\n\n📊 ENTRAR NA COR: {cor}\n\n⏰ Aguardando para realizar a jogada');
insert into double_traducao (chave, valor) values ('MSG_BET_2', '🐓 Martingale {protecao} realizado 🐓\n💸 Valor: R$ {value}');
insert into double_traducao (chave, valor) values ('MSG_BET_3', '✅✅✅');
insert into double_traducao (chave, valor) values ('MSG_BET_4', 'Bot parou, Stop LOSS atingido.');
insert into double_traducao (chave, valor) values ('MSG_BET_5', 'Bot parou, Stop WIN atingido.');
insert into double_traducao (chave, valor) values ('MSG_BET_6', 'Não bateu! 😥');
insert into double_traducao (chave, valor) values ('MSG_BET_7', 'Você não tem mais banca para jogar, seu bot foi parado.');
insert into double_traducao (chave, valor) values ('MSG_BET_8', 'Seu bot foi parado, você não tem mais banca para jogar.');
insert into double_traducao (chave, valor) values ('MSG_BET_9', 'Suas jogadas gratuitas terminaram, seu bot foi parado');
insert into double_traducao (chave, valor) values ('MSG_CADASTRO', 'Olá {usuario}, faça seu cadastro clicando no botão abaixo.');
insert into double_traducao (chave, valor) values ('MSG_CICLO_1', 'Quando a recuperação estiver habilitada, a próxima jogada após o Loss irá utilizar o valor total perdido na jogada anterior. \n\nPor exemplo se você estiver utilizando esta configuração\n\n💲 Sua entrada será de 2,0\n🐓 Você está utilizado 1 gale(s)');
insert into double_traducao (chave, valor) values ('MSG_CICLO_2', 'Quando ocorrer um **Loss** sua perda será de 6, onde 2 da sua primeira entrada e 4 da Gale 1\nCom a recuperação habilitada na próxima jogada será utilizado como valor de entrada 6 no lugar do 2, para que possamos recuperar o valor perdido.');
insert into double_traducao (chave, valor) values ('MSG_CICLO_3', 'Nas demais jogadas voltamos a utilizar o valor 2 como entrada.\n\nVocê {ciclo}está usando a recuperação.');
insert into double_traducao (chave, valor) values ('MSG_CICLO_4', 'Deseja habilitar o uso da recuperação?');
insert into double_traducao (chave, valor) values ('MSG_CICLO_5', 'Você habilitou o uso da recuperação.');
insert into double_traducao (chave, valor) values ('MSG_CICLO_6', 'Você desabilitou o uso da recuperação.');
insert into double_traducao (chave, valor) values ('MSG_CICLO_7', 'Recuperação');
insert into double_traducao (chave, valor) values ('MSG_CLIQUE_BOTAO_ABAIXO', 'Clique no botão abaixo para continuar');
insert into double_traducao (chave, valor) values ('MSG_CONFIGURAR', '➡️Seu robô está com a seguinte configuração:\n\n💸 Valor aposta: {value}\n🐓 Gales: {gales}\n✅ Stop WIN: {stop_win}\n❌ Stop LOSS: {stop_loss}\n↪️ Recuperação: {ciclo}\n🔄 Entrada automática: {entrada_automatica}\n\nSe você desejar alterar algum valor, por favor selecione uma das opções.');
insert into double_traducao (chave, valor) values ('MSG_CONFIRMADO_AGUARDANDO', '⚠️🚨ENTRADA CONFIRMADA🚨⚠️\n\n📊 ENTRAR NA COR: {cor}\n\n⏰ Aguardando para realizar a jogada');
insert into double_traducao (chave, valor) values ('MSG_CONTA_ATIVADA', 'Conta ativada com data de expiração para {dia_expiracao}.');
insert into double_traducao (chave, valor) values ('MSG_DESLOGAR', 'Logout realizado com sucesso.');
insert into double_traducao (chave, valor) values ('MSG_EMAIL_COMPRA', 'Qual seu e-mail de compra?');
insert into double_traducao (chave, valor) values ('MSG_ENTRADA_AUTOMATICA_1', 'Ao ativar a entrada automática a cada Stop WIN atingido o bot irá entrar automaticamente na opção 🚀 Iniciar após LOSS.');
insert into double_traducao (chave, valor) values ('MSG_ENTRADA_AUTOMATICA_10', 'Informe a quantidade de ocorrências de espera que você deseja? \nO novo  valor tem que ser superior a 0!');
insert into double_traducao (chave, valor) values ('MSG_ENTRADA_AUTOMATICA_11', 'Você alterou a quantidade de ocorrências de espera para {quantidade}.');
insert into double_traducao (chave, valor) values ('MSG_ENTRADA_AUTOMATICA_12', 'Você pode habilitar a recuperação para a entrada automática após atingir o Stop LOSS.');
insert into double_traducao (chave, valor) values ('MSG_ENTRADA_AUTOMATICA_13', 'Você habilitou a recuperação para a entrada automática após atingir o Stop LOSS.');
insert into double_traducao (chave, valor) values ('MSG_ENTRADA_AUTOMATICA_14', 'Você desabilitou a recuperação para a entrada automática após atingir o Stop LOSS.');
insert into double_traducao (chave, valor) values ('MSG_ENTRADA_AUTOMATICA_15', 'Escolha qual o tipo de espera para a entrada automática');
insert into double_traducao (chave, valor) values ('MSG_ENTRADA_AUTOMATICA_16', 'Você escolheu esperar para esperar um {tipo} para entrada automática');
insert into double_traducao (chave, valor) values ('MSG_ENTRADA_AUTOMATICA_2', 'Deseja habilitar?');
insert into double_traducao (chave, valor) values ('MSG_ENTRADA_AUTOMATICA_3', 'Você habilitou entrada automática.');
insert into double_traducao (chave, valor) values ('MSG_ENTRADA_AUTOMATICA_4', 'Você desabilitou a entrada automática.');
insert into double_traducao (chave, valor) values ('MSG_ENTRADA_AUTOMATICA_5', 'Você pode habilitar a entrada automática a cada Stop LOSS atingido.');
insert into double_traducao (chave, valor) values ('MSG_ENTRADA_AUTOMATICA_6', 'Você habilitou entrada automática para o Stop WIN e Stop LOSS.');
insert into double_traducao (chave, valor) values ('MSG_ENTRADA_AUTOMATICA_7', 'Você manteve a entrada automática apenas para o Stop WIN.');
insert into double_traducao (chave, valor) values ('MSG_ENTRADA_AUTOMATICA_8', 'Por padrão a entrada automática espera 1 ocorrência.');
insert into double_traducao (chave, valor) values ('MSG_ENTRADA_AUTOMATICA_9', 'Deseja aumentar a quantidade de ocorrências de espera?');
insert into double_traducao (chave, valor) values ('MSG_ERRO_NUMERO', 'Por favor repita a operação e informe um número válido.');
insert into double_traducao (chave, valor) values ('MSG_GALES_1', 'O número de Gales atual é {gales}.');
insert into double_traducao (chave, valor) values ('MSG_GALES_2', 'Informe o número de Gales');
insert into double_traducao (chave, valor) values ('MSG_GALES_3', 'O número de Gales foi configurado para {gales}.');
insert into double_traducao (chave, valor) values ('MSG_INICIO_ROBO_1', 'Você deve fazer o login primeiro.');
insert into double_traducao (chave, valor) values ('MSG_INICIO_ROBO_2', 'Você deve informar um valor de aposta superior a {valor}.');
insert into double_traducao (chave, valor) values ('MSG_INICIO_ROBO_3', 'Sua banca deve ser superior a  {valor}.\nPara uma boa performance do bot recomendamos um depósito de 50,00 para cima.\n\nCaso você precise inserir saldo em sua conta clique no botão abaixo.');
insert into double_traducao (chave, valor) values ('MSG_INICIO_ROBO_4', '➡️ Ligando o robô 🤖\n Sua licença expira no dia {dia_expiracao}');
insert into double_traducao (chave, valor) values ('MSG_INICIO_ROBO_5', '➡️ Ligando o robô 🤖.');
insert into double_traducao (chave, valor) values ('MSG_INICIO_ROBO_6', '➡🔸 Olá {usuario} 🔹\n💰A sua banca é de {banca} \n💲 Sua entrada será de {value}\n🐓 Você está utilizado {gales} gale(s)\n✅ Seu Stop Win está programado para {stop_win}\n❌ Seu Stop Loss está programado para {stop_loss}\n↪️ Recuperação: {ciclo}\n🔄 Entrada automática: {entrada_automatica}');
insert into double_traducao (chave, valor) values ('MSG_INICIO_ROBO_7', '\n🎮 Você tem {demo_jogadas} jogada(s) gratuita(s).');
insert into double_traducao (chave, valor) values ('MSG_INICIO_ROBO_8', 'Não foi possível iniciar o seu bot, suas jogadas gratuitas terminaram.');
insert into double_traducao (chave, valor) values ('MSG_INICIO_ROBO_9', ' robô iniciará após a ocorrência de {quantidade} {tipo}.');
insert into double_traducao (chave, valor) values ('MSG_LOGAR_AGUARDE', 'Aguarde, fazendo login...');
insert into double_traducao (chave, valor) values ('MSG_LOGAR_BANCA', '💰A sua banca é de {banca}.\nPara uma boa performance do bot recomendamos um depósito de 50,00 para cima.\n\nCaso você precise inserir saldo em sua conta clique no botão abaixo.');
insert into double_traducao (chave, valor) values ('MSG_LOGAR_EMAIL', 'Informe seu email da {plataforma}');
insert into double_traducao (chave, valor) values ('MSG_LOGAR_FIM_DEMO', 'Você já utilizou suas 5 entradas gratuitas. Deseja realizar a assinatura e continuar utilizando o bot?');
insert into double_traducao (chave, valor) values ('MSG_LOGAR_INICIO_DEMO', 'Parabéns, você entrou na versão DEMO e terá direito a 5 entradas gratuitas, aproveite!!');
insert into double_traducao (chave, valor) values ('MSG_LOGAR_LOGIN_ERRO', 'Login inválido, por favor refaça a operação.');
insert into double_traducao (chave, valor) values ('MSG_LOGAR_LOGIN_SUCESSO', 'Login realizado com sucesso.');
insert into double_traducao (chave, valor) values ('MSG_LOGAR_PASSOS_CONFIGURACAO', 'Siga os passos para configuração do seu bot.');
insert into double_traducao (chave, valor) values ('MSG_LOGAR_SENHA', 'Informe sua senha');
insert into double_traducao (chave, valor) values ('MSG_OBRIGADO_COMPARTILHAR_DADOS', 'Obrigado por compartilhar seu contato, continue com seu login');
insert into double_traducao (chave, valor) values ('MSG_OPERACAO_CANAL_NAO_SUPORTADO', 'Canal {channel_id} não suportado.');
insert into double_traducao (chave, valor) values ('MSG_OPERACAO_ENTRADA_CICLO', '\n↪️ Recuperação utilizada');
insert into double_traducao (chave, valor) values ('MSG_OPERACAO_ENTRADA_CONFIRMADA', '⚠️🚨ENTRADA CONFIRMADA🚨⚠️\n📊 ENTRAR NA COR: {cor}');
insert into double_traducao (chave, valor) values ('MSG_OPERACAO_ENTRADA_REALIZADA', '🔰 Entrada realizada 🔰\n💸 Valor: R$ {valor}. \n🎯 Cor: {cor}\n');
insert into double_traducao (chave, valor) values ('MSG_OPERACAO_IDENTIFICADO_LOSS', 'Identificada entrada automática, robô irá iniciar as jogadas agora.');
insert into double_traducao (chave, valor) values ('MSG_OPERACAO_MARTINGALE', '🐓 Martingale {protecao} realizado 🐓\n💸 Valor: R$ {valor}');
insert into double_traducao (chave, valor) values ('MSG_OPERACAO_METODO_NAO_SUPORTADO', 'Método não suportado.');
insert into double_traducao (chave, valor) values ('MSG_OPERACAO_NAO_SUPORTADA', 'Operação não suportada.');
insert into double_traducao (chave, valor) values ('MSG_OPERACAO_SERVIDOR_MANUTENCAO', 'Servidor em manutenção.');
insert into double_traducao (chave, valor) values ('MSG_PAGTO_CANCELADO', 'Pagamento de {valor} cancelado com sucesso. Conta com data de expiração para {dia_expiracao}.');
insert into double_traducao (chave, valor) values ('MSG_PARAR_ROBO', '➡️ Robô fechado com sucesso ✅');
insert into double_traducao (chave, valor) values ('MSG_PLATAFORMA_NAO_SUPORTADA', 'Plataforma não suportada');
insert into double_traducao (chave, valor) values ('MSG_REG_NOVO_DIAS', 'Informe o número de dias para expiração do bot');
insert into double_traducao (chave, valor) values ('MSG_REG_NOVO_NAO_ENCONTRADO', 'Usuário {user_id_name} não encontrado no Telegram');
insert into double_traducao (chave, valor) values ('MSG_REG_NOVO_USUARIO', 'Informe user_id ou user_name');
insert into double_traducao (chave, valor) values ('MSG_ROBO_INDISPONIVEL', 'Robô indisponível, tente mais tarde.');
insert into double_traducao (chave, valor) values ('MSG_SELECIONE_OPCAO', 'Selecione uma das opções');
insert into double_traducao (chave, valor) values ('MSG_SINAIS_CADASTRO', '📱 Faça seu cadastro');
insert into double_traducao (chave, valor) values ('MSG_SINAIS_ENTRADA_CONFIRMADA', '⚠️🚨ENTRADA CONFIRMADA🚨⚠️\n\n🔮 TIPO DE ESTRATÉGIA: {estrategia}\n\n📊 ENTRAR NA COR: {cor}\n🎯ENTRAR APÓS: {ultimo_numero} {ultima_cor}\n\n🚨 FUNCIONA SOMENTE NA PLATAFORMA ABAIXO! ⬇️');
insert into double_traducao (chave, valor) values ('MSG_SINAIS_GALE', '🤞🏻 Façam a {protecao} proteção');
insert into double_traducao (chave, valor) values ('MSG_SINAIS_LOSS', 'Não bateu! 😥\n\n⏺️ Opcional: Faça mais um gale ☑️');
insert into double_traducao (chave, valor) values ('MSG_SINAIS_OPORTUNIDADE', '🥁 POSSÍVEL OPORTUNIDADE 🔔');
insert into double_traducao (chave, valor) values ('MSG_SINAIS_PARCIAL_DIA', '🎰 PARCIAL DO DIA 🎰\n\n✅ Win: {win} | ❌ Loss: {loss}\n🤖 Inteligência do Robô: {percentual}%');
insert into double_traducao (chave, valor) values ('MSG_SINAIS_PROJECAO', '📈 PROJEÇÃO DE GANHOS:\nVALOR DE ENTRADA: 20\n\n↪️ RECUPERAÇÃO: Habilitado\n\nVOCÊ ESTARIA COM LUCRO: {valor}');
insert into double_traducao (chave, valor) values ('MSG_SINAIS_SUPORTE', '🆘 Suporte');
insert into double_traducao (chave, valor) values ('MSG_SINAIS_TUTORIAL', '👨‍🏫 Tutorial Double {plataforma}');
insert into double_traducao (chave, valor) values ('MSG_SINAIS_WIN', '✅✅✅');
insert into double_traducao (chave, valor) values ('MSG_STATUS_AG_PGTO', 'Olá, {usuario}. para começar a utilizar o bot é necessário ter cadastro na {plataforma}, clicando no botão abaixo você  poderá realizar seu cadastro.');
insert into double_traducao (chave, valor) values ('MSG_STATUS_DEMO', 'Olá, {usuario}. para começar a utilizar o bot é necessário ter cadastro na {plataforma}, clicando no botão abaixo você  poderá realizar seu cadastro.');
insert into double_traducao (chave, valor) values ('MSG_STATUS_EXPIRADO', 'Olá, {usuario}. Seu plano expirou no dia {dia_expiracao}, caso tenha interesse em assinar, selecione uma das opções abaixo.');
insert into double_traducao (chave, valor) values ('MSG_STATUS_INATIVO', 'Olá, {usuario}. Seu plano está inativo, caso tenha interesse em assinar, selecione uma das opções abaixo.');
insert into double_traducao (chave, valor) values ('MSG_STATUS_NOVO', 'Olá, {usuario}. Seja bem-vindo ao bot automático que opera no jogo double sem precisar de você.');
insert into double_traducao (chave, valor) values ('MSG_STOP_LOSS', 'O Stop LOSS pode ser configurado de duas formas:\n **1) Valor:** O Stop LOSS ocorrerá sempre que o resultado alcançar o valor informado\n **2) Quantidade:** O Stop LOSS ocorrerá sempre que a quantidade de entradas em perda (LOSS) consecutivas o valor informado.\n\nSua configuração atual é:\nTipo: {tipo}\nValor: {valor}');
insert into double_traducao (chave, valor) values ('MSG_STOP_LOSS_1', 'Seu Stop LOSS atual é {stop_loss}.');
insert into double_traducao (chave, valor) values ('MSG_STOP_LOSS_2', 'Informe o valor para Stop LOSS');
insert into double_traducao (chave, valor) values ('MSG_STOP_LOSS_3', 'Seu Stop LOSS foi configurado para {stop_loss}.');
insert into double_traducao (chave, valor) values ('MSG_STOP_LOSS_4', 'Stop LOSS atingido. O robô iniciará após {quantidade} {tipo}.');
insert into double_traducao (chave, valor) values ('MSG_STOP_WIN_1', 'Seu Stop WIN atual é {stop_win}.');
insert into double_traducao (chave, valor) values ('MSG_STOP_WIN_2', 'Informe o valor para Stop WIN');
insert into double_traducao (chave, valor) values ('MSG_STOP_WIN_3', 'Seu Stop WIN foi configurado para {stop_win}.');
insert into double_traducao (chave, valor) values ('MSG_STOP_WIN_4', 'Stop WIN atingido. O robô iniciará após {quantidade} {tipo}.');
insert into double_traducao (chave, valor) values ('MSG_SUPORTE', 'Suporte');
insert into double_traducao (chave, valor) values ('MSG_VALUE_1', 'Seu Valor de aposta atual é {value}.');
insert into double_traducao (chave, valor) values ('MSG_VALUE_2', 'Informe o Valor de aposta');
insert into double_traducao (chave, valor) values ('MSG_VALUE_3', 'Seu Valor de aposta foi configurado para {value}.');
insert into double_traducao (chave, valor) values ('RED', '🔴');
insert into double_traducao (chave, valor) values ('WHITE', '⚪️');
insert into double_traducao (chave, valor) values ('BLACK', '⚫');


SET foreign_key_checks = 1;